### ISSUE TITLE
Support for iscsi volumes and srp 

### ISSUE THREAD

**Issue by crottolo** [ewwhite/zfs-ha#12]
Hi,
I have similar setup and I want deploy your system.
Now I have 2 dell r710,each with 24gb RAM dual xeon quad core, 1 hba,1mellanox 20GB
1 jbod with 12 disk SAS.

On cluster Mgmt si possible add the iscsi conf, or srp? 
The goal is Block storage for VM environment.
Thanks

**Comment by ewwhite** [comment]
iSCSI is possible. It's not my focus since I prefer NFS for VMware use.

However, take a look at this for an iSCSI approach to the HA cluster design:
https://bm-stor.com/index.php/blog/Linux-cluster-with-ZFS-on-Cluster-in-a-Box/

**Comment by Digital-Daz** [comment]
Sorry to revive and old thread but would you mind saying why you prefer NFS over iSCSI.

The internet is littered with different opinion but being as you are the author of this elegant solution it would be great to understand why you chose NFS.

**Comment by efschu** [comment]
Potential reasons are:
- in using iSCSI your machine becomes a SAN, but this guide is describing a NAS (block I/O vs file I/O)
- NFS is much easier to install and to maintain
- if set properly there is almost no performance difference if you are using NFS or iSCSI for VMware storage
- one reason for not using NFS is if you want to go for RoCE (RDMA) instead of TCP/IP, due the lack of NFSoRDMA client for esxi your only option is iSER (iSCSI over RDMA)

So if you still want to go for iSCSI/iSER over NFS you can have a look here

https://github.com/ewwhite/zfs-ha/issues/27#issuecomment-503000513
