### ISSUE TITLE
Performance for ZFS-HA

### ISSUE THREAD

**Issue by v0112358** [ewwhite/zfs-ha#5]
Hello,

I'm interested in your project. Cloud you share some results of disk benchmark (IOPS and bandwidth)?

**Comment by ewwhite** [comment]
Performance depends on your hardware selection and workload. Since we are talking about SAS, the performance does not differ from any direct-attached storage solution. The presence of the high-availability cluster components does not impact performance.

An example:
20 x 7200 RPM disks in RAIDZ1 groups of 5 drives gives me 1 Gigabyte/second writes and nearly the same for reads.

**Comment by v0112358** [comment]
Thank you so much for your valuable information. How about IOPS for random read and write (SAS devices and zeusRAM for ZIL)?

**Comment by ewwhite** [comment]
Again, that performance is going to depend on who's consuming the data, networking interconnect, number and type of disks, etc.
